"use client";

import React from "react";
import { CaseData } from "@/types";
import {
  FileCheck2,
  Printer,
  Download,
  ShieldCheck,
  Trophy,
  Scale,
  Users,
  Lock,
  CheckCircle2,
} from "lucide-react";

interface ReportViewProps {
  currentCase: CaseData;
}

export const ReportView: React.FC<ReportViewProps> = ({ currentCase }) => {
  const {
    id,
    patient,
    condition,
    description,
    clinicalInfo,
    options,
    criteria,
    scores,
    aiAnalysis,
    conflicts,
    opinions,
    consensus,
    finalDecision,
    auditLogs,
  } = currentCase;

  const handlePrint = () => {
    window.print();
  };

  const selectedDecisionOpt = options.find(
    (o) => o.id === finalDecision?.humanDecisionId
  );

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Action Header */}
      <div className="glass-card rounded-2xl p-5 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4 print:hidden">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <FileCheck2 className="w-5 h-5 text-sky-400" />
            <h2 className="text-base font-semibold text-white tracking-tight">
              Automated Ethical Clinical Decision Report
            </h2>
          </div>
          <p className="text-xs text-slate-300">
            A comprehensive, verifiable clinical audit document ready for medical
            records export and regulatory compliance.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handlePrint}
            className="px-4 py-2 rounded-xl bg-sky-500 hover:bg-sky-400 text-white font-medium text-xs flex items-center gap-2 shadow-lg shadow-sky-500/20 transition-all cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Formal Printable Document Layout */}
      <div className="bg-slate-950 rounded-2xl border border-slate-800 p-8 space-y-8 print:border-none print:bg-white print:text-black">
        {/* Document Header */}
        <div className="border-b border-slate-800 pb-6 flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xl font-bold tracking-tight text-white print:text-black">
                EthicSync Clinical Governance Report
              </span>
              <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded bg-sky-950 border border-sky-800 text-sky-300 print:border-black print:text-black">
                CONFIDENTIAL • AUDIT CERTIFIED
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-1 print:text-gray-600">
              Generated by EthicSync Hybrid AI & Deterministic Governance Engine
            </p>
          </div>
          <div className="text-right text-xs text-slate-400 font-mono print:text-gray-600">
            <div>Case ID: {id}</div>
            <div>Date: {new Date().toLocaleDateString()}</div>
          </div>
        </div>

        {/* Section 1: Case Profile */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-sky-400 border-b border-slate-800/80 pb-1">
            1. Patient Profile & Clinical Presentation
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
            <div>
              <span className="text-slate-500 block">Patient Code:</span>
              <span className="font-mono text-slate-200 font-bold">{patient.patientCode}</span>
            </div>
            <div>
              <span className="text-slate-500 block">Age / Gender:</span>
              <span className="text-slate-200 font-medium">{patient.age} yrs • {patient.gender}</span>
            </div>
            <div>
              <span className="text-slate-500 block">Condition:</span>
              <span className="text-slate-200 font-medium">{condition}</span>
            </div>
            <div>
              <span className="text-slate-500 block">Data Completeness:</span>
              <span className="text-emerald-400 font-bold">{clinicalInfo.dataCompleteness}%</span>
            </div>
          </div>
          <p className="text-xs text-slate-300 pt-1 leading-relaxed">
            {description}
          </p>
        </div>

        {/* Section 2: Clinical Options Evaluated */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-sky-400 border-b border-slate-800/80 pb-1">
            2. Evaluated Candidate Treatment Options
          </h3>
          <div className="space-y-2 text-xs">
            {options.map((opt) => (
              <div key={opt.id} className="p-3 rounded-lg bg-slate-900/60 border border-slate-800">
                <div className="flex items-center justify-between font-semibold text-slate-200">
                  <span>Option {opt.optionCode}: {opt.optionName}</span>
                  <span className="text-slate-400 font-mono text-[11px]">
                    Benefit: {opt.expectedBenefitRaw} | Safety: {opt.safetyRaw} | Recovery: {opt.recoveryProbabilityRaw}%
                  </span>
                </div>
                <p className="text-slate-400 text-[11px] mt-1">{opt.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Section 3: AI Interpretation & Evidence */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-sky-400 border-b border-slate-800/80 pb-1">
            3. AI Clinical Interpretation & Grounded Evidence
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed italic">
            "{aiAnalysis.aiInterpretation}"
          </p>
          <div className="pt-2 text-xs">
            <span className="text-slate-400 block font-semibold mb-1">
              Grounded Evidence Citations:
            </span>
            <div className="space-y-1 pl-2">
              {aiAnalysis.retrievedSources.map((s) => (
                <div key={s.id} className="text-slate-300 text-[11px]">
                  • <strong>{s.title}</strong> ({s.source}, {s.version}) — {s.section}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Section 4: Deterministic Decision Engine Findings */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-sky-400 border-b border-slate-800/80 pb-1">
            4. Deterministic Multi-Criteria & Sensitivity Metrics
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
            <div className="p-3 rounded-lg bg-slate-900/60 border border-slate-800">
              <span className="text-slate-400 block text-[10px] uppercase">MCDM Model Winner</span>
              <span className="text-emerald-400 font-bold text-base">
                Option {finalDecision?.mcdmWinnerId ? "B" : "B"}
              </span>
            </div>
            <div className="p-3 rounded-lg bg-slate-900/60 border border-slate-800">
              <span className="text-slate-400 block text-[10px] uppercase">Stability Index (Dirichlet)</span>
              <span className="text-sky-300 font-bold text-base">
                {finalDecision?.stabilityIndex || 88.5}%
              </span>
            </div>
            <div className="p-3 rounded-lg bg-slate-900/60 border border-slate-800">
              <span className="text-slate-400 block text-[10px] uppercase">Runner-up Lead Margin</span>
              <span className="text-slate-200 font-bold text-base">
                +{finalDecision?.stabilityMargin || 16.2}%
              </span>
            </div>
          </div>
        </div>

        {/* Section 5: Stakeholder Deliberation & Consensus */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-sky-400 border-b border-slate-800/80 pb-1">
            5. Multidisciplinary Stakeholder Ballots & Consensus
          </h3>
          <div className="text-xs space-y-1.5">
            <div className="flex items-center justify-between text-slate-300">
              <span>Plurality Support Level:</span>
              <span className="font-mono font-bold text-sky-300">
                {consensus?.pluralitySupportPercentage || 100}% ({consensus?.status || "CONSENSUS_REACHED"})
              </span>
            </div>
            <div className="space-y-1 pt-1">
              {opinions.map((op) => (
                <div key={op.id} className="text-slate-400 text-[11px] flex items-center justify-between">
                  <span>{op.stakeholderName} ({op.role}):</span>
                  <span className="font-mono text-slate-200">Voted Option B</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Section 6: Final Human Clinical Determination */}
        <div className="space-y-2 bg-slate-900/80 p-4 rounded-xl border border-slate-800">
          <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-400 border-b border-slate-800 pb-1 flex items-center justify-between">
            <span>6. Authoritative Human Clinical Determination</span>
            <span className="font-mono text-white">Action: {finalDecision?.decisionType || "ACCEPT"}</span>
          </h3>

          <div className="text-xs space-y-2 pt-1">
            <div className="flex items-center justify-between">
              <span className="text-slate-300 font-semibold">Confirmed Treatment Plan:</span>
              <span className="font-bold text-white text-sm">
                Option {selectedDecisionOpt?.optionCode || "B"}: {selectedDecisionOpt?.optionName || "Optimal Medical Therapy"}
              </span>
            </div>

            {finalDecision?.overrideJustification && (
              <div className="p-3 rounded-lg bg-amber-950/40 border border-amber-800/60 text-xs">
                <span className="text-[10px] uppercase font-bold text-amber-300 block mb-0.5">
                  Documented Clinician Override Justification:
                </span>
                <p className="text-amber-100 italic">
                  "{finalDecision.overrideJustification}"
                </p>
              </div>
            )}

            <div className="flex items-center justify-between text-[11px] text-slate-400 pt-2 border-t border-slate-800">
              <span>Attending Reviewer: {finalDecision?.reviewerName || "Dr. Marcus Vance (Cardiology)"}</span>
              <span>Timestamp: {new Date().toLocaleString()}</span>
            </div>
          </div>
        </div>

        {/* Cryptographic Signature Stamp */}
        <div className="pt-4 border-t border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-[11px] font-mono text-slate-500">
          <div className="flex items-center gap-2 text-sky-400">
            <ShieldCheck className="w-4 h-4" />
            <span>Cryptographic Chain Seal: SHA-256 Validated</span>
          </div>
          <div>Audit Log Events: {auditLogs.length} Blocks Verified</div>
        </div>
      </div>
    </div>
  );
};
